### PR TITLE
Update SocialMedia.py

### PR DESCRIPTION
**Pull request by Latand**
Just added a link for WhatsApp

### CODE REVIEW

**Comment by HoldOffHunger** [comment]
A link like.... <a href="https://api.whatsapp.com/send?text=blahblahblah">Blah</a>

**Comment by Latand** [comment]
> A link like.... [Blah](https://api.whatsapp.com/send?text=blahblahblah)

yep. What is wrong with it?

**Comment by HoldOffHunger** [comment]
If it's any consolation, the WhatsApp URL's had much less functionality one year ago, when they were removed. =)

**Comment by Latand** [comment]
This is strange, it works on my PC and IPhone

https://1drv.ms/v/s!AgfbBJ2qlQFIgoMK6JRc2A3CC2g-bw

**Comment by Latand** [comment]
I’m not sure I’m able to rewrite this in other languages, but if it works, at least the author can add this

**Comment by HoldOffHunger** [comment]
Interesting.  There's slightly different behavior.

In my video, you'll notice it flashes the text very briefly that's supposed to be sent.  Do you get a review screen of the text after you select who to send it to?  (i.e., you get to know what the text being sent is?)

**Comment by Latand** [comment]
Yes it does
https://1drv.ms/u/s!AgfbBJ2qlQFIgoMLkThGzL0HK5Hk6g

**Comment by HoldOffHunger** [comment]
Going to run some more tests tonight when I have another device.  Being able to review the message being sent is definitely critically important, though.

**Pull request closed without merging**
